### ISSUE TITLE
怎么添加events属性

### ISSUE THREAD

**Issue by minozmin94928** [woai3c/vue-form-maker#10]
例如select组件，我需要添加on-change事件，但是select props我怎么加都没反应。。

**Comment by tjob-slack** [comment]
> 例如select组件，我需要添加on-change事件，但是select props我怎么加都没反应。。
下面这样是可以的，文档里面写的就是on-change，
不过demo里用的onchange，改成on-change就可以了
```
events: {
                'on-change':function(e) {
                  alert('这是一个测试')
                }
              }
```
