### ISSUE TITLE
请问Iview与这个组件的关联关系是如何形成的？

### ISSUE THREAD

**Issue by wlrainbow** [woai3c/vue-form-maker#11]
你好，最近在研究动态表单，看到你的方案觉得很好，但是对于它与第三方组件框架的关系如何形成有点迷茫，求指教？

**Comment by woai3c** [comment]
你可以阅读源代码，这个组件是使用 Vue 的 `render` 函数写的，用 `render` 函数生成对应的 iView 组件。建议你先看看 `render` 函数的[官方文档](https://cn.vuejs.org/v2/guide/render-function.html)。

**Comment by woai3c** [comment]
如果还有疑问 加我qq 411020382

**Comment by tjob-slack** [comment]
用render方案非常棒 ！
