### ISSUE TITLE
请教vue-form-maker在微信小程序如何使用？

### ISSUE THREAD

**Issue by tjob-slack** [woai3c/vue-form-maker#13]
如题。

另外，想要一套代码同时生成web和小程序，需要怎么配置呢？

非常感谢！

vue-form-maker非常棒！

**Comment by woai3c** [comment]
不好意思，这个项目使用的框架是 PC 端 UI 框架，不能在移动端使用。
如果是移动端网站，可以拷贝我的源代码，然后将源码中的 PC 端 UI 组件替换成移动端组件即可。但是小程序用不了 VUE。建议你去网上搜搜有没有小程序相关的库。

**Comment by tjob-slack** [comment]
发现一个mpvue，基于vue.js开发，支持微信小程序。
https://github.com/Meituan-Dianping/mpvue
您看一下，是否可以直接引入呢？

**Comment by woai3c** [comment]
> 发现一个mpvue，基于vue.js开发，支持微信小程序。
> https://github.com/Meituan-Dianping/mpvue
> 您看一下，是否可以直接引入呢？

我这个是 PC 端的 UI 库，你可以替换为移动端的 UI 库引入试试。mpvue 我还没用过，不太了了解。
