### ISSUE TITLE
上传组件的下载问题，图片或者txt会直接打开

### ISSUE THREAD

**Issue by dengxieshuai** [woai3c/vue-form-maker#18]
我们在使用upload上传组件时，当上传了图片或者txt文件，点击下载图片或者txt文件时会直接打开文件在页面上而不是下载，我们希望能够做到下载

**Comment by woai3c** [comment]
1. 如果是点击 URL，则需要后端设置相应的响应头 Content-Disposition，这样才能下载。
2. 另外也可以返回来一个二进制文件，然后自己用 URL.createObjectURL下载。

**Comment by dengxieshuai** [comment]
因为我现在用的是upload组件，然后上传完以后文件是以后列表形式排列显示在按钮下面，我点击就能下载，而且这个下载的动作我们没有实现。那如果想自己定义下载应该怎么做呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月1日(周四) 晚上6:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [woai3c/vue-form-maker] 上传组件的下载问题，图片或者txt会直接打开 (#18)




  
如果是点击 URL，则需要后端设置相应的响应头 Content-Disposition，这样才能下载。 

另外也可以返回来一个二进制文件，然后自己用 URL.createObjectURL下载。 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月1日(周四) 晚上6:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [woai3c/vue-form-maker] 上传组件的下载问题，图片或者txt会直接打开 (#18)




  
如果是点击 URL，则需要后端设置相应的响应头 Content-Disposition，这样才能下载。 

另外也可以返回来一个二进制文件，然后自己用 URL.createObjectURL下载。

**Comment by woai3c** [comment]
> 因为我现在用的是upload组件，然后上传完以后文件是以后列表形式排列显示在按钮下面，我点击就能下载，而且这个下载的动作我们没有实现。那如果想自己定义下载应该怎么做呢？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年4月1日(周四) 晚上6:47 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [woai3c/vue-form-maker] 上传组件的下载问题，图片或者txt会直接打开 (#18) 如果是点击 URL，则需要后端设置相应的响应头 Content-Disposition，这样才能下载。 另外也可以返回来一个二进制文件，然后自己用 URL.createObjectURL下载。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年4月1日(周四) 晚上6:47 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [woai3c/vue-form-maker] 上传组件的下载问题，图片或者txt会直接打开 (#18) 如果是点击 URL，则需要后端设置相应的响应头 Content-Disposition，这样才能下载。 另外也可以返回来一个二进制文件，然后自己用 URL.createObjectURL下载。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

应该是使用 URL.createObjectURL，具体实现可以看一下这个 https://segmentfault.com/q/1010000010493203。
