### ISSUE TITLE
Demos are not working

### ISSUE THREAD

**Issue by lapwat** [woai3c/vue-form-maker#4]
Nothing appears in the bottom right box.

https://runjs.cn/code/3fapiha3
https://runjs.cn/code/cllq3lvm

**Comment by woai3c** [comment]
Are you using the Chrome browser?

Browsers sometimes restrict the JS plug-ins of a Web site to run, which indicates risks.

So when you open the DEMO page, copy any URL in the top left corner of the DEMO page, then open the page and go back to the DEMO page to refresh it.
```
<script type="text/javascript" src="https://sandbox.runjs.cn/uploads/rs/137/k9y03ooh/vue.min.js"></script>
<script type="text/javascript" src="https://sandbox.runjs.cn/uploads/rs/137/k9y03ooh/iview.min.js"></script>
<script type="text/javascript" src="https://sandbox.runjs.cn/uploads/rs/137/k9y03ooh/vue-generate-form.js"></script>
```
Just like those URLs above, you copy any one of them on the DEMO website, open it on the page and refresh it to see DEMO.

**Comment by lapwat** [comment]
I am in Firefox browser. It works now thank you. I had to add https://sandbox.runjs.cn certificate to exceptions because it is an "untrusted" source.

**Comment by woai3c** [comment]
You're welcome. This site is relatively small. I'm considering putting DEMO on another site.
