### ISSUE TITLE
变名字了吗

### ISSUE THREAD

**Issue by 869123771** [woai3c/vue-form-maker#5]
以前不是叫vue-generate-form吗 现在都变了吗?

**Comment by woai3c** [comment]
只是名字变了 功能没变 因为我npm账号被盗了 原来的npm包找不回来了 只能从新申请了一个账号 发布新的包 这次我做了更安全的密保方式

**Comment by 869123771** [comment]
喔喔，好像那个文档网站也打不开了。。那以后用我的package.json 里面的包名也要换过来吧？

**Comment by woai3c** [comment]
是的 换名字了 你可以直接卸载以前的包 重新安装现在的 文档地址也要换成现在的

**Comment by woai3c** [comment]
给你带来不便 很抱歉

**Comment by 869123771** [comment]
你这太客气了.
