### ISSUE TITLE
502 http code

### ISSUE THREAD

**Issue by xiejinhe** [woai3c/vue-form-maker#6]
demo link is 502 http code for runjs

**Comment by woai3c** [comment]
There was a mistake on this website.

Direct access is also 502

You'll try again later.

If this website fails later, I will put my DEMO on another website.

**Comment by woai3c** [comment]
Tomorrow I will put DEMO on the new website.

**Comment by woai3c** [comment]
demo的网站挂了 现在正在新的网站上挂demo 不过时间有限目前只写了一个 剩下的将留到下周完成

https://jsrun.net/yJXKp/edit

**Comment by xiejinhe** [comment]
Thanks you very much quick reply!
