### ISSUE TITLE
Button没有事件么

### ISSUE THREAD

**Issue by evaporation777** [woai3c/vue-form-maker#8]
Button没有关于click的event?

**Comment by evaporation777** [comment]
好吧,通过控制台找到了 events 里面应该是 'click':function(){}

**Comment by woai3c** [comment]
如你所述，在 `events` 里放置要绑定的事件。下面是生成按钮组件的函数，在`on` 属性就是监听按钮事件用的
```js
function generateButtonComponent(h, formData = {}, obj) {
    return h('Button', {
        props: obj.props,
        slot: obj.slot,
        style: obj.style,
        on: obj.events
    }, [obj.text])
}
```

**Comment by tjob-slack** [comment]
请教input的events是on-click,为什么button的events是click?
同时，在文档里面，也没有提到click? 是因为click是iview默认的events吗？  多谢啊。
![image](https://user-images.githubusercontent.com/60630538/79346658-35d81700-7f65-11ea-8c23-4f7fcb9ea927.png)

**Comment by woai3c** [comment]
`on-click` 是 iview 组件提供的，click 是 DOM 元素原生的。

**Comment by woai3c** [comment]
> `on-click` 是 iview 组件提供的，click 是 DOM 元素原生的。



> 请教input的events是on-click,为什么button的events是click?
> 同时，在文档里面，也没有提到click? 是因为click是iview默认的events吗？ 多谢啊。
> ![image](https://user-images.githubusercontent.com/60630538/79346658-35d81700-7f65-11ea-8c23-4f7fcb9ea927.png)

`on-click` 是 iview 组件提供的，click 是 DOM 元素原生的。
