### ISSUE TITLE
vue-form-maker表单验证的时候，有些元素的验证时好时坏

### ISSUE THREAD

**Issue by yangying2** [woai3c/vue-form-maker#9]
vue-form-maker表单验证的时候，有些元素的验证时好时坏，而且不是每次某个元素。

**Comment by woai3c** [comment]
你好 可以把代码复制上来吗

**Comment by woai3c** [comment]
表单验证可以设定为仅对某个元素验证，也可设置对多个元素验证，主要取决于规则的编写。

**Comment by yangying2** [comment]
动态表单是在Modal中写的，然后给表单添加元素是在methods方法中写的，父元素打开的时候掉这个方法。

renderdata(lxId,id){
            var _this = this;
            _this.options.formData = {
                propNo:"",
                propName:"",
                description:"",
                gainDescription:"",
                id:"",//数据的id
                fjId: lxId,//类型id  
            }
            _this.options.formItem = [    
                {
                    type: 'input',
                    label: '名称',
                    key: 'name',
                    props: {
                        placeholder: '请输入',
                        type: 'input'
                    },
                    rules: {
                        required: true,
                        trigger: 'blur',
                        message: '请输入'
                    }
                },
                {
                    type: 'input',
                    label: '获取途径描述',
                    key: 'gainDescription',
                    props: {
                        placeholder: '请输入',
                        type: 'textarea'
                    },
                    rules: {
                        required: true,
                        trigger: 'blur',
                        message: '请输入'
                    }
                },
            ];  
            axios.request({
                url: "/xxxx/"+ lxId,
                method: "POST"
            }).then(function(res) {
                if(res.status == 200){
                    var asyncFunc = function(arr, i) {
                        return new Promise(function(resolve, reject) {
                            axios.request({
                                url: "/list/" + arr[i].attributeCode,
                                method: "post"
                            }).then(function(res) {
                                let data = res.data.object;
                                let children = [];
                                for(var j = 0; j < data.length ; j++){
                                    children.push({
                                        value: data[j].attributeCode + data[j].enmCode,
                                        label: data[j].enmName,
                                    })
                                }
                                _this.options.formData[arr[i].attributeCode] = children.length > 0 ? children[0].value : ""
                                _this.options.formItem.push({
                                    type: 'select',
                                    key: arr[i].attributeCode,
                                    label: arr[i].attributeName,
                                    children: children,
                                    props: {
                                        placeholder: '请选择',
                                    },
                                    rules: {
                                        required: true,
                                        message: '请选择',
                                        trigger: 'change'
                                    }
                                })
                                resolve();  
                            });
                        });
                    }
                    let arr = res.data.object
                    var box = async function() {
                        for (let i = 0; i < arr.length ; i++) {
                                // 1 下拉框   2 输入框  3 上传
                            if(arr[i].attributeType == 1){    
                                await asyncFunc(arr, i);
                            }else if(arr[i].attributeType == 2){
                                _this.options.formData[arr[i].attributeCode] = ""
                                _this.options.formItem.push({
                                    type: 'input',
                                    key: arr[i].attributeCode,
                                    label: arr[i].attributeName,
                                    props: {
                                        placeholder: '请输入...',
                                    },
                                    rules: {
                                        required: true,
                                        message: '请输入',
                                        trigger: 'blur'
                                    }
                                })
                            }
                        }
                        console.log(arr);
                    } 
                    var p = new Promise(function (resolve, reject) {
                        resolve();
                    });
                    p.then(box)
                    .then(detail)
                    function detail(){
                        if(id){
                            _this.options.formData.id = id;
                            axios.request({
                                url: "/prop/getInfo/" + id ,
                                method: "post"
                            }).then(function(res) {
                                if(res.data.code == 200){
                                    let resdata = res.data.object
                                    for(var n in  _this.options.formData){
                                        if(n == "fjId" || n == "id"){
                                            _this.options.formData[n] = _this.options.formData[n]
                                        }else if(n == "propNo" || n == "propName"|| n == "description"|| n == "gainDescription"){
                                            _this.options.formData[n] = resdata[n]
                                        }else{
                                            _this.options.formData[n] = resdata.attributeEumMapCode[n]
                                        }  
                                    }     
                                }                      
                            });
                        }
                    } 
                }
            }); 
        },

**Comment by woai3c** [comment]
看了一下代码 没什么问题 建议你把代码文件或项目代码发给我看看 qq 411020382
